services:
  - type: worker
    name: line-bot-worker
    env: python
    region: oregon
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    autoDeploy: true
    envVars:
      - key: LINE_TOKEN
        sync: false
      # أو استخدم البريد وكلمة المرور:
      # - key: LINE_EMAIL
      #   sync: false
      # - key: LINE_PASSWORD
      #   sync: false
